"""
weekly_reporter.py — Auto weekly performance report.
Pulls real stats from analytics.db and velocity.db.
Sends formatted report to Telegram + Discord every Sunday.
Also generates a local text report you can read anytime.
"""
from __future__ import annotations
import json, logging, sqlite3, time, urllib.parse, urllib.request
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional

log = logging.getLogger(__name__)


class WeeklyReporter:

    def __init__(self, queue_dir: Path, cfg: dict):
        self.queue_dir   = Path(queue_dir)
        self.analytics_db = self.queue_dir / "analytics.db"
        self.velocity_db  = self.queue_dir / "velocity.db"
        notif = cfg.get("notifications", {})
        self.tg_token    = notif.get("telegram", {}).get("token", "")
        self.tg_chat     = notif.get("telegram", {}).get("chat_id", "")
        self.discord_hook= notif.get("discord",  {}).get("webhook_url", "")
        self.channel     = cfg.get("branding", {}).get("channel_name", "AutoReels")

    def generate_report(self, days: int = 7) -> str:
        """Build the full weekly report string."""
        since = time.time() - days * 86400
        stats = self._pull_stats(since)

        lines = [
            f"📊 *{self.channel} — Weekly Report*",
            f"📅 {datetime.now().strftime('%d %b %Y')} (last {days} days)\n",
            f"📤 *Uploads:* {stats['total_uploads']}",
            f"▶️  *Total Views:* {stats['total_views']:,}",
            f"❤️  *Total Likes:* {stats['total_likes']:,}",
            f"💬 *Avg Engagement:* {stats['avg_engagement']:.2f}%",
            f"🚀 *Viral Clips:* {stats['viral_count']}",
            f"🔁 *Platforms:* {', '.join(stats['platforms'])}",
        ]

        if stats["top_clips"]:
            lines.append("\n🏆 *Top Performers:*")
            for i, clip in enumerate(stats["top_clips"][:3], 1):
                lines.append(f"  {i}. {clip['title'][:35]} — "
                              f"{clip['views']:,} views ({clip['engagement']:.1f}% eng)")

        if stats["best_time"]:
            lines.append(f"\n⏰ *Best Upload Time:* {stats['best_time']}")

        lines.append(f"\n_Generated by AutoReels v10 • {datetime.now().strftime('%H:%M')}_")
        return "\n".join(lines)

    def send(self, days: int = 7) -> bool:
        """Generate and send report to all configured channels."""
        report = self.generate_report(days)
        log.info("[Reporter] sending weekly report (%d chars)", len(report))

        sent_any = False
        if self.tg_token and self.tg_chat and not self.tg_token.startswith("${"):
            sent_any |= self._send_telegram(report)
        if self.discord_hook and not self.discord_hook.startswith("${"):
            sent_any |= self._send_discord(report)

        # Always save to file
        report_path = self.queue_dir / f"report_{datetime.now().strftime('%Y%m%d')}.txt"
        report_path.write_text(report.replace("*", "").replace("_", ""), encoding="utf-8")
        log.info("[Reporter] saved to %s", report_path)

        return sent_any

    def print_report(self, days: int = 7):
        print(self.generate_report(days).replace("*", "").replace("_", ""))

    # ── Data Pulling ──────────────────────────────────────────────────────────

    def _pull_stats(self, since: float) -> dict:
        stats = {
            "total_uploads": 0, "total_views": 0, "total_likes": 0,
            "avg_engagement": 0.0, "viral_count": 0,
            "platforms": [], "top_clips": [], "best_time": "",
        }

        if not self.analytics_db.exists():
            return stats

        try:
            conn = sqlite3.connect(self.analytics_db, timeout=10)

            # Basic counts
            row = conn.execute("""
                SELECT COUNT(*), SUM(p.views), SUM(p.likes), AVG(p.engagement)
                FROM uploads u
                JOIN performance p ON p.upload_id = u.id
                WHERE u.uploaded_at >= ?
            """, (since,)).fetchone()
            if row and row[0]:
                stats["total_uploads"]  = row[0] or 0
                stats["total_views"]    = int(row[1] or 0)
                stats["total_likes"]    = int(row[2] or 0)
                stats["avg_engagement"] = round(float(row[3] or 0), 2)

            # Platforms
            plats = conn.execute(
                "SELECT DISTINCT platform FROM uploads WHERE uploaded_at >= ?", (since,)
            ).fetchall()
            stats["platforms"] = [r[0] for r in plats]

            # Top clips
            top = conn.execute("""
                SELECT u.title, p.views, p.engagement
                FROM uploads u JOIN performance p ON p.upload_id = u.id
                WHERE u.uploaded_at >= ?
                ORDER BY p.views DESC LIMIT 5
            """, (since,)).fetchall()
            stats["top_clips"] = [{"title": r[0] or "Untitled",
                                    "views": r[1] or 0,
                                    "engagement": r[2] or 0.0}
                                   for r in top]
            conn.close()
        except Exception as e:
            log.debug("[Reporter] analytics query error: %s", e)

        # Viral count from velocity DB
        if self.velocity_db.exists():
            try:
                conn2 = sqlite3.connect(self.velocity_db, timeout=10)
                row2 = conn2.execute(
                    "SELECT COUNT(*) FROM velocity_uploads WHERE viral_triggered=1 AND uploaded_at >= ?",
                    (since,)
                ).fetchone()
                stats["viral_count"] = row2[0] if row2 else 0
                conn2.close()
            except Exception:
                pass

        # Best posting hour
        try:
            conn3 = sqlite3.connect(self.analytics_db, timeout=5)
            row3 = conn3.execute("""
                SELECT strftime('%H', datetime(uploaded_at,'unixepoch')) as hour,
                       AVG(p.engagement) as avg_eng
                FROM uploads u JOIN performance p ON p.upload_id=u.id
                WHERE u.uploaded_at >= ?
                GROUP BY hour ORDER BY avg_eng DESC LIMIT 1
            """, (since,)).fetchone()
            if row3:
                stats["best_time"] = f"{row3[0]}:00 ({row3[1]:.1f}% avg engagement)"
            conn3.close()
        except Exception:
            pass

        return stats

    # ── Sending ───────────────────────────────────────────────────────────────

    def _send_telegram(self, text: str) -> bool:
        url  = f"https://api.telegram.org/bot{self.tg_token}/sendMessage"
        data = urllib.parse.urlencode({
            "chat_id": self.tg_chat, "text": text[:4000],
            "parse_mode": "Markdown",
        }).encode()
        try:
            with urllib.request.urlopen(
                urllib.request.Request(url, data=data, method="POST"), timeout=15
            ) as resp:
                result = json.loads(resp.read())
            ok = result.get("ok", False)
            if ok:
                log.info("[Reporter] Telegram sent ✅")
            return ok
        except Exception as e:
            log.warning("[Reporter] Telegram failed: %s", e)
            return False

    def _send_discord(self, text: str) -> bool:
        # Discord doesn't support Markdown bold with * — strip them
        clean = text.replace("*", "**").replace("_", "")
        body  = json.dumps({"content": clean[:2000]}).encode()
        try:
            req = urllib.request.Request(
                self.discord_hook, data=body,
                headers={"Content-Type": "application/json"}, method="POST",
            )
            with urllib.request.urlopen(req, timeout=15):
                pass
            log.info("[Reporter] Discord sent ✅")
            return True
        except Exception as e:
            log.warning("[Reporter] Discord failed: %s", e)
            return False
