#!/usr/bin/env python3
"""
convert_cookies_json_to_netscape.py
====================================
Convert a JSON cookie export (e.g. from the "Get cookies.txt LOCALLY" browser
extension) into the Netscape/Mozilla cookies.txt format accepted by yt-dlp.

Usage:
    python convert_cookies_json_to_netscape.py <input.json> <output.txt>

Exit codes:
    0  – conversion succeeded
    1  – argument error or unreadable input
    2  – input file could not be parsed as JSON cookies
"""
from __future__ import annotations

import json
import math
import sys
from pathlib import Path


NETSCAPE_HEADER = "# Netscape HTTP Cookie File\n# Generated by AutoReels-Pro\n\n"


def _bool_str(value: object) -> str:
    """Return 'TRUE' or 'FALSE' from a truthy/falsy Python value."""
    return "TRUE" if value else "FALSE"


def _convert(data: list[dict]) -> str:
    """Build a Netscape cookie file string from a list of JSON cookie dicts."""
    lines: list[str] = [NETSCAPE_HEADER]
    converted = 0
    for cookie in data:
        domain: str = cookie.get("domain", "")
        include_subdomains: bool = cookie.get("domain", "").startswith(".")
        path: str = cookie.get("path", "/")
        secure: bool = cookie.get("secure", False)
        # expirationDate may be float; 0 / missing → session cookie (use 0)
        expiry_raw = cookie.get("expirationDate", cookie.get("expiry", 0)) or 0
        try:
            expiry_float = float(expiry_raw)
            expiry: int = 0 if math.isnan(expiry_float) else int(expiry_float)
        except (TypeError, ValueError):
            expiry = 0
        name: str = cookie.get("name", "")
        value: str = cookie.get("value", "")

        if not name:
            continue  # skip nameless cookies

        line = "\t".join([
            domain,
            _bool_str(include_subdomains),
            path,
            _bool_str(secure),
            str(expiry),
            name,
            value,
        ])
        lines.append(line + "\n")
        converted += 1
    return "".join(lines), converted


def main() -> int:
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input.json> <output.txt>", file=sys.stderr)
        return 1

    input_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    try:
        raw = input_path.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"Cannot read {input_path}: {exc}", file=sys.stderr)
        return 1

    # Accept both a top-level list and a dict wrapper (e.g. {"cookies": [...]})
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError as exc:
        print(f"JSON parse error: {exc}", file=sys.stderr)
        return 2

    if isinstance(parsed, dict):
        # Some exporters wrap the list: {"cookies": [...]}
        for key in ("cookies", "cookie", "data"):
            if isinstance(parsed.get(key), list):
                parsed = parsed[key]
                break
        else:
            print("JSON object found but no 'cookies' / 'cookie' / 'data' list key.", file=sys.stderr)
            return 2

    if not isinstance(parsed, list):
        print("Expected a JSON array of cookie objects.", file=sys.stderr)
        return 2

    netscape_content, converted = _convert(parsed)

    try:
        output_path.write_text(netscape_content, encoding="utf-8")
    except OSError as exc:
        print(f"Cannot write {output_path}: {exc}", file=sys.stderr)
        return 1

    print(f"Converted {converted} of {len(parsed)} cookies → {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
